language: node_js
dist: bionic
cache:
  npm: true
  directories:
    - ~/.cache
node_js:
  - "12"
stages:
  - test
  - name: build
    if: branch IN (develop, master)
  - name: deploy
    if: branch = master AND type = push
jobs:
  include:
    - stage: test
      name: "Frontend Lint"
      before_install: cd frontend
      script:
        - npm run lint
    - name: "Backend Lint"
      language: python
      python:
        - "3.6"
      script: make lint
    - name: "Frontend Unit Tests"
      before_install: cd frontend
      script:
        - npm run test:unit
    - name: "Backend Unit Tests"
      services:
        - mongodb
      language: python
      python:
        - "3.6"
      script:
        - make unit
    - name: "E2E Tests"
      services:
        - mongodb
      before_install:
        - sudo apt-get install xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 python3 python3-pip python3-setuptools python3-wheel
        - pip3 install -r requirements.txt
        - cd frontend
      script:
        - cd ..
        - ./run-e2e-tests.sh
