language: node_js
cache:
  npm: true
  directories:
    - ~/.cache 
node_js:
  - "12"
stages:
  - test
  - name: build
    if: branch IN (develop, master)
  - name: deploy
    if: branch = master AND type = push
jobs:
  include:
    - stage: test
      name: "Lint"
      install:
        - cd frontend
        - npm i
      script:
        - npm run lint
    - name: "Unit Tests"
      install:
        - cd frontend
        - npm i
      script:
        - npm run test:unit
    - name: "E2E Tests"
      install:
        - sudo apt-get install xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2
        - cd frontend
        - npm i
      script:
        - npm run test:e2e:ci
    - stage: build
      script:
        - echo Coming soon...
    - stage: deploy
      script:
        - echo Coming soon...
